language: node_js
node_js:
  - node
email:
  on_failure: change
  on_success: never
deploy:
  provider: npm
  skip_cleanup: true
  email:
    secure: "NKsHgOMx4thcUWCN67ZZqq7s2gIk3wwutUt2MdJvmw7pmkDlTNSeH53hKsPQovVYG0Bzdf1gwzlninNWHKRy6LR6S7UsRGrTutPM5HzCITv2fbvo+IzZZ8iG2wTtJXB4Xyi+hP1Xf0VC1ikRulcA78Blbuo03Q/YwFN7vn28Cpn5Yod8gJU+HxKv7v/DK/mf6SpPjMUPz/NAf5kTmxhIKVH/vTI5c+sobkacGPUipG5AmvZFCGOkTsSS3Kk1XU3ZrvQNHDcvOLUnAlLd6ko6cisGNed9fAc7RXJCxNzOcTBoCNvfs76638N0yzuA8lCGAmiR9ex3+YRtF43/YV9O0xSCPg77nJBUvwMWRROptAgOD+tJD704RzU4ztoi1tzYv16OA1bAeBzs7DlViAUjGZKGB9/aHllWqMQh+xnID4LYSb9IYElC0LPMKsIZgXEf0NQIltENjjoMWUnbRTaUeJnq5RwhznYSXOvJZVuYzVeQhjNXGR/orUMKWI3Hnn/pd9FLake5SVlAoG03xwjmyxeEKxyckQref8rqntX+/0RLFTZECvfjtnglKz68SnMDrduYLs3zDNO6WX9QilT+EJ/f4PMU3csJTeOi1VZaqLRzSLNaRtQwUD9hWx4M4Yn7bmLeEct58GxrIKFeh+pm0puWLt9TmI0tj4mLnIa+pbQ="
  api_key:
    secure: "IzstPGNxWMYd8P6G56HdYWZLly8SUxyJbnwSi1K5+YAMuRw9VG6RjomjvQN/plD/oYkwTAzpZ9axCCjrzQ9/B38hLcusMZ8f23kmzoQrHHG5TmI0Qec6IuAEtQPUiGZ2VPduUM/tq0hMHMJBGf1ZWsHiWs6xA9rzG6Qcj532Kung4BfUxYf+zZu48e8g+obKgGmP/9uxexVgfl90FbBWK+DgiNpqjP5hga6dAYKJ+mawidaURvNphuvKVhQQ9NdeXgWDu9g95LtFrWc6vgqGoDh1tCZDhtVC5ZKyCYANwhsj96ykFDqnSp+55HKC/BqXIcwL3xM6p4ftgkuZ8krRxacvs7QdQD5/bf6hr7T+tZIyKlX7ab2jlrqZ/+IEybOIG4tUG1R+jkY+I8Bo/L0H0lptW16bj9Tpw9F/RtesPv/KJpSNRmVJG34pi749nBK8kpb3BOKPzgmlHKqFLpNGkReT7b3EXw+pOe7JX2Uc4LIsyR5NILLm5UwuEjdwtBe5BskFp5RX7xYlY1pVoJsI/OvOOYaKGHGItc1nAK2bbwTcRi3tpuP9dk01v11tIw8ToOlwJCVVHkgoE3n4tINKONQMRkrFXeOVpkyZup/qVF25vzV4Ok58h/cgKFOxthXP+y3xVfC8s3J4rFLFCt2PvsbFvVa+O4kfSKZWMTooSnk="
  on:
    branch: master
    repo: groundbreaker/qewl-forms
